import { useEffect } from "react";
import { useRouter } from "next/router";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const router = useRouter();
  useEffect(() => {
    router.push("/Explore");
  }, [router]);

  return (
    <Head>
      <title>Portugal app</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Home;
